id: product_holon_v0
kind: part
name: Product holon v0
mass: 0.0
unit: kg
material_class: software
notes: 'Product holon - represents product requirements and processes; placeholder
  holon used by seed: paper_reviews_dec2024_comprehensive_v0. Massless software agent.'
recipe: recipe_product_holon_v0_v0
